### PR TITLE
Update existing_data_standards.md

### PR DESCRIPTION
**Pull request by rachelshekar**

### CODE REVIEW

**Comment by dlebauer** [comment]
@craig-willis could you please review and update this page (feel free to merge this pull request and start fresh if you prefer). I think that the document you wrote does a good job of covering the relevant details.

**Comment by craig-willis** [comment]
Sure, I'm preparing a separate PR with the information from the Google Doc.

**Comment by craig-willis** [comment]
I've never used Gitbook -- is the pdf build error common?

**Comment by dlebauer** [comment]
Don't worry about the pdf build failure - its a typo somewhere that I need
to track down

**Pull request merged**
